### ISSUE TITLE
FAQ section in some pages is blank

### ISSUE THREAD

**Issue by Vicopem01** [Aview-International/aviewint-website#121]
<img width="1425" alt="Screenshot 2023-10-25 at 11 27 32 AM" src="https://github.com/Aview-International/aviewint-website/assets/82455026/678f7c89-6193-4156-8777-f759c8e942ab">

**Comment by chandhuDev** [comment]
@Vicopem01 We have different FAQ's for each page. So we have to create new FAQ's for every page.
