### ISSUE TITLE
Voice cloning page redesign

### ISSUE THREAD

**Issue by Vicopem01** [Aview-International/aviewint-website#173]

**Comment by Vicopem01** [comment]
@chandhuDev

**Comment by chandhuDev** [comment]
Thanks @Vicopem01 for mentioning it! I think it's happened in saving the ai-voice samples, am I crct? Or can you please ping me which commit is that one! I can look into it in more detail

**Comment by Vicopem01** [comment]
yes, in the ai-voice samples

**Comment by Vicopem01** [comment]
@chandhuDev figma design in ready to go

**Comment by Vicopem01** [comment]
https://www.figma.com/file/PMfG3eyLRvDwQ2iG2QXUmK?node-id=2899:13245&mode=design#642434959

**Comment by chandhuDev** [comment]
Yup no problem
