### ISSUE TITLE
Dashboard videos gets doubled

### ISSUE THREAD

**Issue by Vicopem01** [Aview-International/aviewint-website#190]

**Comment by Vicopem01** [comment]
![Image](https://github.com/Aview-International/aviewint-website/assets/82455026/31005dc0-543f-4cdd-988e-4daa11eeba3e)

I noticed the function that gets the social media videos gets called twice

**Comment by Vicopem01** [comment]
@Bobliuuu can we get fix for this

**Comment by Vicopem01** [comment]
@chandhuDev

**Comment by chandhuDev** [comment]
perfect I will look into that

**Comment by Vicopem01** [comment]
@chandhuDev  this issue still happens

**Comment by chandhuDev** [comment]
yeah, i havent worked on this one till now as I should have to connect youtube to check how it is displaying . And also previous issue(aligning the videos in correct height) as well depends on connecting socials to check. but you mentioned local server is in under development. Okk I will try mimicking this one with dummy data then

**Comment by Vicopem01** [comment]
any progress on this?

@chandhuDev

**Comment by chandhuDev** [comment]
Hey @Vicopem01   we have already talked about this, since it needs YouTube connection to test how it's working on my lappy, present system is redirecting to blank page not the dashboard , you mentioned we gonna make a new test server.. that is why it's on hold!

**Comment by Vicopem01** [comment]
oh okay.

while i am yet to configure the local server, you'll notice that the api request in the useEffect in the dashboard is running twice , can we get a fix for that?

**Comment by Vicopem01** [comment]
if you check your network tab, all the api calls run twice cos of react component mounting

**Comment by chandhuDev** [comment]
yup! sure not a problem. Will check

**Comment by Vicopem01** [comment]
any progress on this @chandhuDev ?

**Comment by chandhuDev** [comment]
hey in socials youtube got rectified and works fine, but not Instagram as it has not connected yet!
