### ISSUE TITLE
Slider UI design

### ISSUE THREAD

**Issue by Vicopem01** [Aview-International/aviewint-website#203]

**Comment by Vicopem01** [comment]
Checkout to a new branch `slider`.

There is a component that is commented out in the index.js file in pages.

That is the slider that needs to be completed

**Comment by Vicopem01** [comment]
Also, the slider component is used in pricing page, so any changes made to it will also affect pricing page. You can make changes to it as long as the pricing page remains same (I would recommend not making changes at all)

**Comment by chandhuDev** [comment]
hey I don't see any commented out component in index.js

**Comment by chandhuDev** [comment]
hey I don't see any commented out component in index.js
