### ISSUE TITLE
New dashboard page

### ISSUE THREAD

**Issue by Vicopem01** [Aview-International/aviewint-website#246]

**Comment by Vicopem01** [comment]
##  check this
- hello
- here
[x] checked
[ ] not checked

**Comment by Vicopem01** [comment]
hey

**Comment by d-huliu** [comment]
Hi victor, is this a real task for me to work on, or is my first real task later

**Comment by Vicopem01** [comment]
it's a real task. 

Assigning the rest soon. But let's get this done to A/B test it

**Comment by d-huliu** [comment]
sorry what is A/B, and how do I get started on this task

**Comment by Vicopem01** [comment]
oh wait lmao

**Comment by Vicopem01** [comment]
this is not a real task, i got it mixed up

**Comment by Vicopem01** [comment]
i'm gonna delete this, this was just a sample to show you how it's done

**Comment by d-huliu** [comment]
lmfao

**Comment by d-huliu** [comment]
the button change is a real task correct.
