### ISSUE TITLE
Change homepage CTA text

### ISSUE THREAD

**Issue by Vicopem01** [Aview-International/aviewint-website#247]
![Image](https://github.com/Aview-International/aviewint-website/assets/82455026/ef804c6f-4fbc-45c6-9209-5418b47d4de5)

### The text in the dark button says "Login". Please change it to "Sign up"

**Comment by Vicopem01** [comment]
@d-huliu , remember, switch to the beta branch, checkout to a new working branch `git checkout -b cta-text`. 

when you make the change, add and commit the change and push to the new branch `git push origin cta-text`. 

then create a pull request and tag me to it, also add this task in the *Developement section* on the left

**Comment by d-huliu** [comment]
Thank you. I'm not quite sure which folder contains the code for the homepage

**Comment by Vicopem01** [comment]
in the index.js file, you'll see each breakdown of the components, arranged according to where they render on the UI, you just have to track it down further

**Comment by d-huliu** [comment]
sorry, the login button is in the header right, and the index.js is under which page? I'm seeing too many index.js
