### ISSUE TITLE
Dashboard popup fix

### ISSUE THREAD

**Issue by Vicopem01** [Aview-International/aviewint-website#252]
![Image](https://github.com/Aview-International/aviewint-website/assets/82455026/6c92360f-3d09-4320-8d5f-23f73c2200b7)

## Modal does not close when clicked outside.

**Comment by Vicopem01** [comment]
![Image](https://github.com/Aview-International/aviewint-website/assets/82455026/50959957-ccee-437b-8e3d-7723e8ee2572)


### let's also revert the loading icon back to the previous one

**Comment by Vicopem01** [comment]
@chandhuDev did you get this

**Comment by chandhuDev** [comment]
@Vicopem01 yup

**Comment by Vicopem01** [comment]
@d-huliu , let's pick this up

**Comment by d-huliu** [comment]
okay, sounds good

**Comment by d-huliu** [comment]
how does this modal even appear? I have my own Aview account and I don't know how to make the popup appear. I went through some of the components like dashboard. Not sure what I'm looking for exactly

**Comment by Vicopem01** [comment]
let's connect tomorrow at 9:30, to walk through the dashboard
