### ISSUE TITLE
Distribution account connection settings

### ISSUE THREAD

**Issue by Vicopem01** [Aview-International/aviewint-website#268]
### In the image below, we want to connect other social media accounts for creators who probably skipped it during onboarding or wan to switch account.

I know @chandhuDev already started working on this, but while chandhu is not available, @d-huliu please pick this up to get it completed.

Also, to close this modal, we want to add a close button and also click outside of this component to close the modal

![Image](https://github.com/Aview-International/aviewint-website/assets/82455026/a401ac63-6fa9-4e4e-b2d3-428c8c881d81)

**Comment by Vicopem01** [comment]
#262 is the work in progress so far, check it for more info

**Comment by chandhuDev** [comment]
As this one is extended version for #262 , you could easily assume it as one issue where we have to remove the static data that is present now , should display the present socials data that is the logo / image and channel name. At present system , we cant show the subscribers. 
And we not gonna show multiple accounts , how it is present now in the screenshot only one social account per one social.

**Comment by chandhuDev** [comment]
@d-huliu
